owner: 'oswald'
schedule_interval: "@daily"
dag_id: templated_ent_cbs_ad_summary_loads
dag_description: Testing templating with Jinja
default_args:
  - key: 'owner'
    value: 'oswald',
  - key: 'depends_on_past'
    value: False
  - key: 'start_date'
    value: datetime(2019, 1, 1)
  - key: 'email'
    value: ['oswald.ramirez@cbsinteractive.com']
  - key: 'email_on_failure'
    value: True
  - key: 'email_on_retry'
    value: False
  - key: 'retries'
    value: 3
  - key: 'retry_delay'
    value: timedelta(minutes=5)
  - key: 'max_active_runs'
    value: 1
  - key: 'catchup'
    value: False
params:
  - key: APP_DIR
    value: APP_DIR
  - key: ROOT_DIR
    value: ROOT_DIR
  - key: TEMP_DIR
    value: TEMP_DIR
  - key: GCP_SERVICE_ACCOUNT_KEY
    value: GCP_SERVICE_ACCOUNT_KEY
  - key: GC_BQ_PROJECT
    value: GC_BQ_PROJECT
  - key: GC_BQ_DATASET
    value: GC_BQ_DATASET
  - key: SRC_TABLE_1
    value: SRC_TABLE_1
  - key: DEST_TABLE_1
    value: DEST_TABLE_1
  - key: DATE_FILTER
    value: DATE_FILTER
  - key: DAY_DT_NODASH
    value: day_dt_nodash
  - key: DAY_DT_DASH
    value: day_dt_dash
bq_tasks:
  - task_name: rm_summary_table_data
    sql_file_path: entertainment/ent_cbs_ad_summary_loads/sql/rm_pt_cbs_dfp_ad_summ_day.sql
    dependencies: check_cs_events
  - task_name: insert_summary_table_data
    sql_file_path: entertainment/ent_cbs_ad_summary_loads/sql/insert_pt_cbs_dfp_ad_summ_day.sql
    dependencies: rm_summary_table_data
py_tasks:
  - task_name: rm_summary_table_data
    python_callable: test1.py
    dependencies: check_cs_events
  - task_name: insert_summary_table_data
    python_callable: test2.py
    dependencies: rm_summary_table_data
